### ISSUE TITLE
do not track header

### ISSUE THREAD

**Issue by Duneyr** [matomo-org/tracker-proxy#23]
First of all, many thanks for this proxy. Very helpful!
I found one tiny issue though: If piwik is configured to respect the dnt-track header, this proxy does not seem to respect that (more precisely: does not forward this header to piwik). So piwik does not receive the header and tracks the corresponding user anyway.

**Comment by mattab** [comment]
Thanks for the report @Duneyr - that's a good find. We would welcome a pull request for fixing this issue! :+1:

**Comment by level420** [comment]
Added new PR https://github.com/matomo-org/tracker-proxy/pull/32 with DNT support for the tracker.

**Comment by mattab** [comment]
Thanks @level420 for the PR which has been merged
