### ISSUE TITLE
Support for Heatmaps & Session Recordings

### ISSUE THREAD

**Issue by mattab** [matomo-org/tracker-proxy#26]
Currently the tracker-proxy does not work along with the Sessions and Heatmaps recording features from https://plugins.piwik.org/HeatmapSessionRecording

We would need to also handle & proxy the requests to `plugins/...../configs.php` files.

This is not trivial as we would need to either use redirect rules to catch all `plugin/xxx/configs.php`calls, or use `.htaccess` rules which wouldn't work on all webservers. So we'd likely neeed to manually create the files `plugins/XYZ/configs.php` acting as proxy.

**Once implemented notify customer in ticket 6207 and 6899 and HS #47035 to let them know**

**Comment by tsteur** [comment]
Is it possible to rebuild the same folder structure in the proxy so no redirects etc needed? And for manual installation add instructions so they also add the same directory in their website?

**Comment by mattab** [comment]
Yes it should be possible to have the same folder structure, as long as it won't conflict with users existing rewrite rules etc.  Most of the time should be fine for sure.
