### ISSUE TITLE
<noscript> compatibility

### ISSUE THREAD

**Issue by futureweb** [matomo-org/tracker-proxy#31]
it would be good if the tracker-proxy script could also handle the <noscript> requests like original tracker.

Andreas Schnederle-Wagner

**Comment by mattab** [comment]
Hi @futureweb
 did you try it already, and is it not working?

**Comment by futureweb** [comment]
Hey @mattab, 
unfortunately we had not much time the last weeks as we are in the middle of GDPR preps in our company ... :-/

In Tracker Proxy Doc is written:

> the <noscript> part of the code at the end is removed, since it is not currently used by Piwik, and it contains the (secret) Piwik URL which you want to hide

Is this outdated? Or did I overlook something?

**Comment by mattab** [comment]
we say it's removed, not sure if it's supported or not, but it should be supported and already I think.
