### ISSUE TITLE
no tracking - installed the proxy script as described

### ISSUE THREAD

**Issue by meentix** [matomo-org/tracker-proxy#45]
Hi,

Ive updated the old piwik.php and replaced it with the current version. So Ive downloaded and uploaded piwik.php, proxy.php, matomo-proxy.php & plugins/HeatmapSessionRecording/configs.php to my webspace, you can access them at http://www.psyheu.de/piwik.php, http://www.psyheu.de/proxy.php, http://www.psyheu.de/matomo-proxy.php & http://www.psyheu.de/plugins/HeatmapSessionRecording/configs.php - Ive also set $PIWIK_URL and $TOKEN_AUTH in the proxy.php and changed the js-snippet as you can see in source code of http://www.psyheu.de - but there is no working tracking any longer, I dont know why. It worked with the old piwik proxy script but now its not :-( How can I find out the problem?

**Comment by meentix** [comment]
Nobody has an idea? :-(

**Comment by level420** [comment]
@meentix did you also check the `config.php` file and the `TOKEN_AUTH` therein?

**Comment by meentix** [comment]
Which config.php? Ive used the manual installation by downloading the four mentioned files and setting the correct $PIWIK_URL and $TOKEN_AUTH in the proxy.php. Ive done this with two other projects (that means without a config.php too) the same and the tracking is working there :-/

**Comment by level420** [comment]
Ah OK then you've modified `proxy.php`. I prefer using the `config.php` file as it allows me to leave `proxy.php` unchanged.

Do you see any access to the matomo instance (access log of the http-server where the matomo instance is living on) when visiting a page at http://www.psyheu.de ?

**Comment by level420** [comment]
Also on http://www.psyheu.de/datenschutz/ in the matomo section there is not the opt iframe/checkbox visible, but a login window. I think this is not intended?!?!?

**Comment by meentix** [comment]
Yes, Ive modified proxy.php.

Yeah I see access and an error, here is one example:

2018-05-28 16:31:38 | Error | xxx | 400 | GET /piwik.php?cip=xxx&amp;token_auth=xxx&amp;action_name=www.psyheu.de%2FUngew%C3%B6hnliche+Sex-Praktiken&amp;idsite=4&amp;rec=1&amp;r=409968&amp;h=16&amp;m=31&amp;s=38&amp;url=http%3A%2F%2Fwww.psyheu.de%2F6744%2Fsexuelle-praktiken-perversion-paraphilie%2F&amp;urlref=android-app%3A%2F%2Fcom.google.android.googlequicksearchbox&amp;_id=b0ad0a49fff7fee2&amp;_idts=1527517899&amp;_idvc=1&amp;_idn=0&amp;_refts=1527517899&amp;_viewts=1527517899&amp;_ref=android-app%3A%2F%2Fcom.google.android.googlequicksearchbox&amp;send_image=1&amp;cookie=1&amp;res=360x640&amp;gt_ms=347&amp;pv_id=vkVIu8  HTTP/1.0 |   |   | 3.85 K | SSL/TLS-Zugriff für Apache
-- | -- | -- | -- | -- | -- | -- | -- | --
2018-05-28 16:31:38 | Error | xxx |   | AH01071: Got error 'PHP message: Error in Matomo (tracker): Invalid idSite: '0'\n' |   |   |   | Apache-Fehler

Ive removed the token_auth and ip address from the link in the logfile (xxx), but they are correct set there . There seems to be a problem with the siteId, but its set in the js code in the tracked site and it is in the refferer url :-/

The problem in the datenschutz-section is also not intended, right.

**Comment by level420** [comment]
@meentix sorry no idea what's wrong. I've compared the GET request you've added with the GET requests on my sites and I can't find a difference regarding the idsite parameter.

You could maybe test if matomo is tracking correctly without the proxy if your matomo instance is reachable from outside. If this works it is clearly the fault of the proxy, if not you should check your matomo installation.

**Comment by meentix** [comment]
The tracking without proxy is working correctly and with the old proxy script everything worked fine before but not with the new one. That means there must be a problem with the new proxy script :-(

**Comment by level420** [comment]
Did you compare the two GET requests? I mean the GET request which is caused against the matomo instance via the proxy and the GET request which is caused against the instance by using the non-proxied method.

And which matomo version are you using? Is it matomo 3.5 (latest is 3.5.1)?

**Comment by meentix** [comment]
They are different of course, but I think that relates to the non-use of the proxy script now:

GET /piwik.php?action_name=www.psyheu.de%2FWahre%20Liebe%3A%20Woran%20erkennt%20man%20sie&idsite=4&rec=1&r=964452&h=11&m=17&s=51&url=http%3A%2F%2Fwww.psyheu.de%2F10315%2Fwahre-liebe-woran-erkennt-man-sie%2F&urlref=https%3A%2F%2Fwww.google.de%2F&_id=8aef1ff58f3c0ef7&_idts=1527671871&_idvc=1&_idn=0&_refts=1527671871&_viewts=1527671871&_ref=https%3A%2F%2Fwww.google.de%2F&send_image=1&cookie=1&res=375x667&gt_ms=364&pv_id=7vv2K4 HTTP/1.1

I also track other sites with the new proxy script and this matomo instance where the tracking works :-/ One exemple:

GET /piwik.php?cip=xxx&token_auth=xxx&action_name=www.unfallrente.net%2FRente+der+Berufsgenossenschaft+%28BG+Rente%29&idsite=3&rec=1&r=278433&h=11&m=20&s=42&url=https%3A%2F%2Fwww.unfallrente.net%2Fgesetzliche-unfallversicherung%2Fberufsgenossenschaft-bg&urlref=https%3A%2F%2Fwww.google.de%2F&_id=6aae842819ea66df&_idts=1527672043&_idvc=1&_idn=0&_refts=1527672043&_viewts=1527672043&_ref=https%3A%2F%2Fwww.google.de%2F&send_image=1&cookie=1&res=360x640&gt_ms=249&pv_id=QGq3Mr HTTP/1.0

Im using the latest one 3.5.1, but Ive also tried it with 3.5 before.

**Comment by level420** [comment]
@meentix sorry, but I'm giving up. No more ideas :-(

**Comment by diosmosis** [comment]
Hi @meentix can you try the following:

* where you set your `$PIWIK_URL` variable, also set `$PROXY_URL` to the tracker proxy URL (in your case `http://www.psyheu.de/`). This is a new requirement, I've made sure the README mentions it.
* if it still doesn't work you can try temporarily setting `$DEBUG_PROXY` to true in `proxy.php`, triggering the proxy and seeing if any PHP errors result.

?

**Comment by meentix** [comment]
Hi @diosmosis 

Ive set the $PIWIK_URL in the proxy.php; where I should set the $PROXY_URL? Ive used the manual installation of the proxy (no use of git or so).

Ive set the $DEBUG_PROXY to true in proxy.php and I dont see any PHP errors, do you see some? I only see the error in the serverlogs:

"2018-06-05 15:42:44 | Error | xxx |   | AH01071: Got error 'PHP message: Error in Matomo (tracker): Invalid idSite: '0'\n' |   |   |   | Apache-Fehler
-- | -- | -- | -- | -- | -- | -- | -- | --"

**Comment by meentix** [comment]
Ive updated the php version from 7.0 to 7.1 yesterday and after it the tracking with proxy works, so I think there was maybe a problem with this special php version (7.0)?

**Comment by diosmosis** [comment]
Glad to hear your issue is resolved! Closing this issue now, feel free to reply or create another issue if you run into another problem.

Re PHP 7.0, tested locally w/ PHP 7.0.35, works for me, let me know if you find a specific issue w/ 7.0 (if you care to look, no worries if not).
