### ISSUE TITLE
content tracking does not work when using the tracker-proxy

### ISSUE THREAD

**Issue by level420** [matomo-org/tracker-proxy#52]
Tracking page views and links works as expected, but content tracking does not work.
I've verified that content tracking does work if I'm using the non proxy javascript tracker.

This is for matomo 3.11.0, php 7.1.31 and current matomo proxy tracker as a fresh clone via git clone.

The matomo instance is running on its own subdomain matomoinstance.mydomain.tld.
piwik.php is accessible through the path /stat/ on each website to be tracked.

Tracker code is:
```javascript
<script type="text/javascript">
  var _paq = window._paq || [];
  _paq.push(['disableCookies']);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  _paq.push(['trackAllContentImpressions']);
  (function() {
    var u="//mysite.mydomain.tld/stat/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type="text/javascript"; g.async=true; g.defer=true; g.src=u+"piwik.php"; s.parentNode.insertBefore(g,s);
  })();
</script>
```

config.php for the proxy:
```php
<?php

$PIWIK_URL = 'https://mymatomoinstance.mydomain.tld/';
$PROXY_URL = '/stat/';
$TOKEN_AUTH = 'someworkingauthtoken';
$timeout = 5;
$user_agent = '';

```

**Comment by tsteur** [comment]
From what I see in the code this should work. Have you been able to investigate a little what could cause this? Or do you mean the "redirect" to a clicked link might not work? This could be the case indeed and we're planning to fix this in Matomo core.

**Comment by level420** [comment]
@tsteur No I mean that I don't get results for content impressions in the visitors log and no results under "Behaviour -> Contents":
![image](https://user-images.githubusercontent.com/210674/63423364-6e424800-c40c-11e9-8f1e-70e710033933.png)

**Comment by level420** [comment]
@tsteur the screenshot shows what happens if I'm using the normal javascript tracker. Those entries are missing if I'm using the proxy tracker.

**Comment by tsteur** [comment]
Thanks @level420 sounds like a bug then. In case you have a chance and are familiar with PHP it be great to check if it uses `fopen` or curl for you see https://github.com/matomo-org/tracker-proxy/blob/master/proxy.php#L236

This would make it eventually easier to find the problem maybe.

Not sure if it's any useful but you could try setting `$DEBUG_PROXY = true;` but not sure it will print any errors in the request or not in this case.

**Comment by level420** [comment]
On our server proxy.php sets ```$useFopen``` to ```'1'```.
I've forced proxy.php using curl, but with the same results.
And I don't know if this is helpful, but setting ```$DEBUG_PROXY``` to ```true``` gets the following message in the php error log:
```
 PHP Notice:  file_get_contents(): Content-type not specified assuming 
application/x-www-form-urlencoded i
n /data/cluster/opt/matomo/proxy.php on line 288
```

**Comment by level420** [comment]
I've digged a bit into what's going on when content tracking is done. In this case there is a post request to the tracker proxy which is handled here: https://github.com/matomo-org/tracker-proxy/blob/master/proxy.php#L274-L281

When comparing the post data sent from the browser (via chrome dev tools in the network tab), I'm seeing that the first post data parameter name is:
```
  {"requests":["?c_n
```
but when I'm inspecting the ```$_POST``` array in proxy.php, the first parameter name is
```
  {"requests":_"?c_n
```
not the that the ```[``` is replaced by an ```_```.

**Comment by tsteur** [comment]
We haven't really had any issues with this so far AFAIK. But I know in bulk tracking plugin we do it basically like this:

```php
$raw = file_get_contents("php://input");
$raw = trim($raw);
$raw = str_replace(array("\n", "\r"), '', $raw);
$POST = json_decode($rawData, $assoc = true);
```

Could you maybe try something like this?

**Comment by level420** [comment]
@tsteur so here comes the first part of the problem which I solved using your hint.

It seems that indeed the current forwarding method of forwarding the POST request through proxy.php to the matomo backend destructs the data when using the ```$_POST``` array to create the post data. I've solved it with this simple change:
```patch
--- proxy.php.orig      2019-08-23 13:13:28.731397554 +0200
+++ proxy.php   2019-08-23 15:21:41.891278807 +0200
@@ -272,7 +272,7 @@
 
     // if there's POST data, send our proxy request as a POST
     if (!empty($_POST)) {
-        $postBody = http_build_query($_POST);
+        $postBody = file_get_contents("php://input");
 
         $stream_options['http']['method'] = 'POST';
         $stream_options['http']['header'][] = "Content-type: application/x-www-form-urlencoded";
```
Now the POST data is forwarded without destruction and the response from the backend gets propated back to the browser which was not the case before.

With 2 elements being marked on the page, I'm getting the response with http code 200:
```json
{"status":"success","tracked":2,"invalid":0}
```
while with the unpatched version the response is a http code 204 without data in response.

After I got this working I realized that the tracked content is not counted for the IP from where I visited the website, but from the IP where the proxy.php is executed from, which means that it is our servers IP!!!

This is definitely wrong as the real IP to track is sent in the ```cip``` field correctly!!!

So every content tracking event is now counted for the servers IP.

I've seen you've already created issue #51 and tried to add the ```X-Forwarded-For``` header in the request to the backend usind the IP from function ```getVisitIp``` in ```proxy.php``` without success.

So again: from what I see the tracker proxy can not work, and possibly never did, for content tracking.

**Comment by level420** [comment]
BTW: I first had disabled tracking for our servers IP, as it was unreasonable for me to track visits if some scripts or monitoring sensors accessed the website. So my first observations with the patched proxy.php and enabled tracker debugging, was that the tracking event was discarded because its IP address was on the global list of excluded IPs.

**Comment by level420** [comment]
In the I fixed this bug. See PR #53

**Comment by tsteur** [comment]
Awesome, cheers @level420

**Comment by andrelung** [comment]
I think I am having the same issue:
https://github.com/matomo-org/tracker-proxy/issues/94

I just realized, that all "wrongly" tracked impressions are originating from the same server:
<img width="500" alt="Image" src="https://github.com/user-attachments/assets/7799138e-fd36-421b-9c94-be1e48f64136" />

<img width="758" alt="Image" src="https://github.com/user-attachments/assets/edbffe79-8d9f-492f-bf6f-1b6d763e711b" />

which turns out to belong to my hoster:
https://db-ip.com/all/82.165.87#:~:text=range%20owned%20by-,IONOS%20SE,-and%20located%20in

The changed code is live in the current commit, right? Are there any specific settings you made?

**Comment by andrelung** [comment]
I just found out, that the shown address matches to `SERVER_ADDR` in the PHP-var `$_SERVER` 

<img width="218" alt="Image" src="https://github.com/user-attachments/assets/260394a7-12fc-40a2-9baf-f9286229a312" />



The correct IP is always in the field `REMOTE_ADDR`
