### ISSUE TITLE
This package about current PHP version requirement

### ISSUE THREAD

**Issue by peter279k** [matomo-org/tracker-proxy#56]
As title, the this package requires `php-5.3` version at least and it defines on [composer.json](https://github.com/matomo-org/tracker-proxy/blob/master/tests/composer.json).

But it says that this will require `php-5.2` version at least on [Requirements](https://github.com/matomo-org/tracker-proxy#requirements) section.

**Comment by tsteur** [comment]
cheers, fixed. I'm not 100% sure but reckon supporting only PHP 5.3+ be fine.
