### ISSUE TITLE
SyntaxError: unexpected token: identifier - The ressource is part of matomo...

### ISSUE THREAD

**Issue by InkFlo** [matomo-org/tracker-proxy#60]
Hi,

I just finished to setup the tracker-proxy but I have the following error in the browser console : `SyntaxError: unexpected token: identifier piwik.php:1:5`

When I tried to open the file I just see this message : 

> This resource is part of Matomo. Keep full control of your data with the leading free and open source <a href='https://matomo.org' target='_blank' rel='noopener noreferrer nofollow'>web analytics & conversion optimisation platform</a>.

Do you have any idea on how to solve this bug ?

Thanks

**Comment by tsteur** [comment]
By the sounds either GET (URL parameters) or POST data is not forwarded for some reason (if I had to guess). Could be maybe also other issues.

**Comment by InkFlo** [comment]
Thanks for helping, I'm using the tracker behind CloudFront as reverse proxy to EC2 origin (with nginx and php-fpm).
Maybe I made a mistake in the configuration... I'll keep you informed if I succeed

**Comment by InkFlo** [comment]
Hi, it was a misconfiguration of my `config.php` file ^^" 
I added **matomo.php** to the `PIWIK_URL` by mistake (matomo-domain.com/matomo.php instead of matomo-domain.com)
