### ISSUE TITLE
tracker-proxy server URL

### ISSUE THREAD

**Issue by ReemaAH** [matomo-org/tracker-proxy#62]
Hello,

I have a question regarding the "$PROXY_URL" in config.php its description isn't very clear.
shall I set up a separate proxy and add its URL here?  or what the value should be exactly?

Thank you!

**Comment by tsteur** [comment]
@ReemaAH 

> // Edit the line below and replace http://your-tracker-proxy.org/ with the URL to your tracker-proxy
> // setup. This URL will be used in Matomo output that contains the Matomo URL, so your Matomo is effectively
> // hidden.
> $PROXY_URL = 'http://your-tracker-proxy.org/';

This means you need to configure the domain/path where you installed this tracker proxy. Eg if it's on your website then it might be `https://your-domain.example.com/tracker-proxy/`
