### ISSUE TITLE
Data sent to `proxy.php` using POST requests are being are passed to Matomo as GET if there are no POST body.

### ISSUE THREAD

**Issue by ducdigital** [matomo-org/tracker-proxy#85]
In the current code, we have a check for `$_POST` if empty here https://github.com/matomo-org/tracker-proxy/blob/master/proxy.php#L284

However, in the latest Matomo tracking, there is a possibility of sending tracking data via POST with URL parameters and without any POST body.

 In my` proxy.php` I changed my code to `$_SERVER['REQUEST_METHOD'] == 'POST'` instead, this solve the issue

**Comment by bx80** [comment]
Thanks for sharing your solution @ducdigital, this is useful information for anyone else wanting to send tracking request as POST with URL parameters :+1:

We don't have any plans to add this as an option to the tracker proxy just at the moment, but if there is wider interest in such an option then we can look at this again. We're also always happy to receive and recognize community pull requests :smiley:
